### ISSUE TITLE
Flattening again, doesn't update all images

### ISSUE THREAD

**Issue by rohapa** [einancunlu/Flatten-Plugin-for-Sketch#1]
After making a flattened image, and making changes on the original and flattening a second time doesn't update the imageholder like it used to. This plugin was amazing to me.

Sketch Version 3.8.3 (29802)

**Comment by einancunlu** [comment]
It doesn't update automatically because Sketch stopped updating symbols automatically. I'm working on this to make it automatic but couldn't manage it yet. You can click on the sync button here to update the image until I fix it:

![screen shot 2016-07-12 at 11 29 16 pm](https://cloud.githubusercontent.com/assets/1511689/16782551/c7f6cc3e-4888-11e6-87f1-fa87f281baea.png)

**Comment by rohapa** [comment]
Thank you, now it's my favorite plugin... again! 
Keep up the great work and thanks for the fastest response ever.

**Comment by einancunlu** [comment]
Happy to hear! : )
