### ISSUE TITLE
Image Mode doesn't work as expected

### ISSUE THREAD

**Issue by ghanbak** [einancunlu/Flatten-Plugin-for-Sketch#14]
Flattening in Layer or Image mode does the same thing by creating a rectangle shape layer and adding an image fill. It'd be nice to add a bitmap layer so can take full advantage of the layer edit and transform tools.

<img width="346" alt="screen shot 2017-12-07 at 1 09 13 pm" src="https://user-images.githubusercontent.com/1842556/33731031-dca4a16e-db4f-11e7-8b0a-84b71720d8dc.png">

**Comment by einancunlu** [comment]
I guess you want to use artboard flattening feature for mirroring an artboard into a device mockup screen, right? 

Using bitmap instead of a shape sounds like a solution, but I don't think it would be that simple. Firstly, a shared style can't be used to fill a bitmap. If you apply a shared style to a bitmap, it would just behave as like a shape rather than a bitmap. So, I would need to solve this problem in another way and probably it wouldn't be easy. There is already a plugin for that: https://magicsketch.io/mirror/
