### ISSUE TITLE
Flatten Artboard issue

### ISSUE THREAD

**Issue by illustree** [einancunlu/Flatten-Plugin-for-Sketch#4]
when selecting Artboard and Flatten, the expected result would be that it would hide all layers and only display the flattened layer. Atm the flattened layer stays hidden after flattening an artboard. please can you fix?

**Comment by einancunlu** [comment]
Hello, sorry for late answer, I didn't saw it. 

This is the expected behavior, when you flatten an artboard it doesn't show the image by default. Because in most of the cases you would be editing the artboards continuously. If your case is special, you need to do it manually for now. I might add a setting for this in the future, but I don't have much time recently, so not sure if it would happen soon.

**Comment by illustree** [comment]
I actually must disagree.... when you click Flatten you would expect it to flatten also for artboards ... but thanks for your time
