### ISSUE TITLE
Shared Style prompt not showing up

### ISSUE THREAD

**Issue by ilustrebruno** [einancunlu/Flatten-Plugin-for-Sketch#6]
Flatten plugin (1.3) won’t prompt the user to create a Shared Style anymore. It just creates the flattened layer, not the Shared Style.

**Comment by davekover** [comment]
I just wanted to chime in and confirm that this issue is occurring on Sketch 45.1 (43504). Since the shared style is not created at all, there is no way to utilize the flattened element elsewhere.

Repro Steps:

1. Select Artboard
2. Choose Plugins -> Flatten -> Flatten Selection

Expected Result: Shared style dialog appears
Actual Result: No dialog appears or shared style created, however the flattened layer is created.

**Comment by einancunlu** [comment]
Hey guys, updated the plugin! : )
